### ISSUE TITLE
Fix the mod-doc test in src/visitor/mod.rs

### ISSUE THREAD

**Issue by phrohdoh** [Phrohdoh/tsqlust#9]
```
running 1 test
test visitor_0 ... FAILED

failures:

---- visitor_0 stdout ----
	error[E0405]: trait `Visitor` is not in scope
 --> <anon>:5:6
  |
5 | impl Visitor for MyVisitor {
  |      ^^^^^^^ `Visitor` is not in scope
  |
  = help: you can import it into scope: `use tsqlust::visitor::Visitor;`.

error[E0412]: type name `Context` is undefined or not in scope
 --> <anon>:6:52
  |
6 |     fn visit_select_statement(&mut self, ctx: &mut Context, select_statement: &SelectStatement) { }
  |                                                    ^^^^^^^ undefined or not in scope
  |
  = help: you can import it into scope: `use tsqlust::diagnostics::Context;`.

error[E0412]: type name `SelectStatement` is undefined or not in scope
 --> <anon>:6:80
  |
6 |     fn visit_select_statement(&mut self, ctx: &mut Context, select_statement: &SelectStatement) { }
  |                                                                                ^^^^^^^^^^^^^^^ undefined or not in scope
  |
  = help: you can import it into scope: `use tsqlust::ast::SelectStatement;`.

error[E0412]: type name `Context` is undefined or not in scope
 --> <anon>:7:49
  |
7 |     fn visit_top_statement(&mut self, ctx: &mut Context, top_statement: &TopStatement) {
  |                                                 ^^^^^^^ undefined or not in scope
  |
  = help: you can import it into scope: `use tsqlust::diagnostics::Context;`.

error[E0412]: type name `TopStatement` is undefined or not in scope
 --> <anon>:7:74
  |
7 |     fn visit_top_statement(&mut self, ctx: &mut Context, top_statement: &TopStatement) {
  |                                                                          ^^^^^^^^^^^^ undefined or not in scope
  |
  = help: you can import it into scope: `use tsqlust::ast::TopStatement;`.

error[E0531]: unresolved struct, variant or union type `Diagnostic`
 --> <anon>:8:28
  |
8 |         ctx.add_diagnostic(Diagnostic {
  |                            ^^^^^^^^^^

error[E0433]: failed to resolve. Use of undeclared type or module `DiagnosticType`
 --> <anon>:9:30
  |
9 |             diagnostic_type: DiagnosticType::Error,
  |                              ^^^^^^^^^^^^^^^^^^^^^ Use of undeclared type or module `DiagnosticType`

error: cannot continue compilation due to previous error

thread 'visitor_0' panicked at 'Box<Any>', ../src/librustc/session/mod.rs:198
stack backtrace:
   1:        0x110f0d18a - std::sys::imp::backtrace::tracing::imp::write::h944c02ac40aee2d7
   2:        0x110f1a44f - std::panicking::default_hook::{{closure}}::h6875a2976258b020
   3:        0x110f19ffd - std::panicking::default_hook::h88ffbc5922643264
   4:        0x110f1a916 - std::panicking::rust_panic_with_hook::ha5aed1dfc0e220e3
   5:        0x10d83ae4a - std::panicking::begin_panic::hd94ce9155ea3657f
   6:        0x10d9cd14b - rustc::session::Session::fatal::h1bd4874c25cf4e1a
   7:        0x10d548cfe - <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::trait_def_id::hb0af984d7d13d012
   8:        0x10d5561c9 - <rustc_typeck::collect::CollectItemTypesVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'v>>::visit_item::hb56a5e568897341c
   9:        0x10d555924 - rustc_typeck::collect::collect_item_types::hbb793d6bbce555f2
  10:        0x10d578f25 - rustc_typeck::check_crate::h4045752b69a796e8
  11:        0x10c78010c - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::h97a3a12d948df547
  12:        0x10c77d362 - rustc_driver::driver::phase_3_run_analysis_passes::hb0ad9de18d423e67
  13:        0x10c7645ed - rustc_driver::driver::compile_input::h8e119234b60571d5
  14:        0x10c2f8b44 - std::panicking::try::do_call::h0a8ee4ecf741923a
  15:        0x110f1ceca - __rust_maybe_catch_panic
  16:        0x10c40916d - rustdoc::test::runtest::hf495a779c1a7f98a
  17:        0x10c2fcb40 - <F as test::FnBox<T>>::call_box::h3ee4137b6798604c
  18:        0x110f1ceca - __rust_maybe_catch_panic
  19:        0x10c664798 - std::panicking::try::do_call::h08f37655de48bcd8
  20:        0x110f1ceca - __rust_maybe_catch_panic
  21:        0x10c66b2fa - <F as alloc::boxed::FnBox<A>>::call_box::haaca8f8edff0a78c
  22:        0x110f19594 - std::sys::imp::thread::Thread::new::thread_start::h8084b1107992ae5b
  23:     0x7fffe7a86aba - _pthread_body
  24:     0x7fffe7a86a06 - _pthread_start
thread 'visitor_0' panicked at 'couldn't compile the test', ../src/librustdoc/test.rs:261
stack backtrace:
   1:        0x110f0d18a - std::sys::imp::backtrace::tracing::imp::write::h944c02ac40aee2d7
   2:        0x110f1a44f - std::panicking::default_hook::{{closure}}::h6875a2976258b020
   3:        0x110f19ffd - std::panicking::default_hook::h88ffbc5922643264
   4:        0x110f1a916 - std::panicking::rust_panic_with_hook::ha5aed1dfc0e220e3
   5:        0x10c2f85c4 - std::panicking::begin_panic::h5f0a1fd8f4de57ec
   6:        0x10c40ac73 - rustdoc::test::runtest::hf495a779c1a7f98a
   7:        0x10c2fcb40 - <F as test::FnBox<T>>::call_box::h3ee4137b6798604c
   8:        0x110f1ceca - __rust_maybe_catch_panic
   9:        0x10c664798 - std::panicking::try::do_call::h08f37655de48bcd8
  10:        0x110f1ceca - __rust_maybe_catch_panic
  11:        0x10c66b2fa - <F as alloc::boxed::FnBox<A>>::call_box::haaca8f8edff0a78c
  12:        0x110f19594 - std::sys::imp::thread::Thread::new::thread_start::h8084b1107992ae5b
  13:     0x7fffe7a86aba - _pthread_body
  14:     0x7fffe7a86a06 - _pthread_start


failures:
    visitor_0

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
```

**Comment by phrohdoh** [comment]
This was fixed in 07df855c9917725f2ebe1f3e6770f678d6b81f66.
